baseurl: https://example.com
title: Hugo DPSG
languageCode: en
DefaultContentLanguage: en
paginate: '10'
theme: hugo-dpsg
Author:
  avatar: img/avatar.png
  bio: Registrasi dan Statistik Untirta
  name: Registrasi
Params:
  authorbox: yes
  copyright: DGSP local group
  dateformat: 02.01.2006
  description: Selamat datang di website Subbagian Registrasi!
  footer:
    text: '[Imprint and Privacy](/imprint)'
  indexPager: yes
  logo:
    header: img/ss.jpg
    image: img/untirta.png
    subtitle: Universitas Sultan Ageng Tirtayasa
    title: Registrasi dan Statistik
  mainSections:
    - post
    - blog
    - news
  opengraph: yes
  pager: yes
  post_meta:
    - author
    - date
    - categories
    - translations
  readmore: yes
  schema: yes
  sidebar:
    home: right
    list: left
    single: no
    widgets:
      - search
      - recent
      - categories
      - taglist
      - social
      - languages
  style:
    vars:
      highlightColor: '#003056'
  toc: yes
  twitter_cards: yes
  widgets:
    recent_num: 5
    tags_counter: yes
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
